### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by dbclkh** [dmt-software/jms-soap-serializer#13]
Hello,

I'm trying to get your Soap Serializer to work with my webservice but I'm having some problems with it :-(

I am trying to get the following envelope:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://domain.com">
  <SOAP-ENV:Body>
    <ns1:searchRequest>
      <ns1:query>my query goes here.</ns1:query>
....

But at the moment all the tags are changed to lowercase :-/ 

<soap:envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:body>
    <searchrequest xmlns=""> 

Is this by design or am I just missing some little configuration?

Regards - Lars Hansen

**Comment by dbclkh** [comment]
Never mind - figured it out :)

**Comment by proggeler** [comment]
Hi Lars. 

I see you already figured is out.
Is it something I could improve or document better?

Regards, Bas

**Comment by dbclkh** [comment]
Hello Bas,

I thought it was changing the camelcase names to lowercase.
But the the request is actually ok - it’s apparently the response that is giving me a hard time.

One thing that did give me a headache was this error message:

throw new RuntimeException('Missing XmlRootName or XmlRootNamespace for ' . $event->getType()['name']);

It took me a while to figure out that I was missing an annotation on my request class.

/**
 * @XmlRoot("searchRequest", namespace = "")
 * @NS("searchRequest")
 */
class SearchRequest {

This would be a great help for others - I think :-)

Venlig hilsen/Best regards
Lars Krogsgård Hansen
ProduktUdvikling - Frontend
DBC as

www.dbc.dk<http://www.dbc.dk>
lkh@dbc.dk

Den 12. mar. 2019 kl. 14.51 skrev Bas de Mes <notifications@github.com<mailto:notifications@github.com>>:


Hi Lars.

I see you already figured is out.
Is it something I could improve or document better?

Regards, Bas

**Comment by dbclkh** [comment]
Hi Bas,

I hope you don’t mind me writing to you directly - but I’m kind of stuck :-/

I’ve gotten the request (serialization) up and running now, but the response (deserialization) is giving me a bit of headache.

In the SoapMessageEventSubscriper.php -> getMessage you check if the namespace is located in the static::SOAP_NAMESPACES.

A var_dump of the $element->getNamespaces() and static::SOAP_NAMESPACES for my soap webservice gives this output:


/var/www/html/vendor/dmt-software/jms-soap-serializer/src/SoapMessageEventSubscriber.php:76:
array (size=1)
  'oa' => string 'http://oss.dbc.dk/ns/openagency' (length=31)


/var/www/html/vendor/dmt-software/jms-soap-serializer/src/SoapMessageEventSubscriber.php:77:
array (size=2)
  1 => string 'http://schemas.xmlsoap.org/soap/envelope/' (length=41)
  2 => string 'http://www.w3.org/2003/05/soap-envelope' (length=39)


EXCEPTION THROWN: Unsupported SOAP version

I have the following annotation for the response calls:


/**
 * @XmlRoot("findLibraryResponse", namespace = "http://oss.dbc.dk/ns/openagency")
 * @XmlNamespace(uri="http://oss.dbc.dk/ns/openagency")
 */
class FindLibraryResponse {

Is my code missing some annotation or should there be some kind of addSoapNamespace to the SoapNamespaceInterface class (or similar class)?

Venlig hilsen
Lars Krogsgård Hansen
ProduktUdvikling - Frontend
DBC as

www.dbc.dk<http://www.dbc.dk>
lkh@dbc.dk

Den 12. mar. 2019 kl. 14.51 skrev Bas de Mes <notifications@github.com<mailto:notifications@github.com>>:


Hi Lars.

I see you already figured is out.
Is it something I could improve or document better?

Regards, Bas

**Comment by wickedOne** [comment]
have you tried the prefix annotation?
```php
@Serializer\XmlNamespace(uri="http://oss.dbc.dk/ns/openagency", prefix="ns1")
```

**Comment by wickedOne** [comment]
never mind my previous comment, it appears your namespace is incorrect.
would you be able to supply the soap response you're trying to deserialize?

**Comment by dbclkh** [comment]
Hi,

The namespace is incorrect, and it cannot be changed :-/


<?xml version="1.0" encoding="UTF-8”?>

  <oa:findLibraryResponse xmlns:oa="http://oss.dbc.dk/ns/openagency" xmlns="http://oss.dbc.dk/ns/openagency”>

    <oa:pickupAgency>…….

So if the SoapNamespaceInterface could have some kind of addNamespace - then I could add my namespace there.

Thank you VERY much for your time - it is highly appreciated

Venlig hilsen
Lars Krogsgård Hansen
ProduktUdvikling - Frontend
DBC as

www.dbc.dk<http://www.dbc.dk>
lkh@dbc.dk

Den 29. mar. 2019 kl. 09.51 skrev wickedOne <notifications@github.com<mailto:notifications@github.com>>:


never mind my previous comment, it appears your namespace is incorrect.
would you be able to supply the soap response you're trying to deserialize?

**Comment by proggeler** [comment]
Hi Lars.

The example is not a SOAP response (it is missing the soap envelop and body).
If you want to de-serialize this kind of xml you should fall back to the default jms deserialize xml type:
`
$serializer = \JMS\Serializer\SerializerBuilder::create();
$libraryResponse = $serializer->deserialize($your_xml_response, FindLibraryResponse::class, 'xml');
`

**Comment by wickedOne** [comment]
you're trying to deserialize the "findLibraryResponse", but am quite sure that isn't the raw xml you get from the soap client which should be something like

```xml
<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:m="http://www.example.org">
...
```
so if you could supply the raw soap response (so the part from ``<xml`` up until ``<oa:findLibraryResponse ...``) you're trying to deserialize, we might figure something out

**Comment by dbclkh** [comment]
Hi Bas,

You’re right - the request is a SOAP but the response isn’t… I am so blind :-(

I’ll give the regular deserializer a go and let you know how it goes.

Venlig hilsen
Lars Krogsgård Hansen
ProduktUdvikling - Frontend
DBC as

www.dbc.dk<http://www.dbc.dk>
lkh@dbc.dk

Den 29. mar. 2019 kl. 10.15 skrev wickedOne <notifications@github.com<mailto:notifications@github.com>>:


you're trying to deserialize the "findLibraryResponse", but am quite sure that isn't the raw xml you get from the soap client which should be something like

<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:m="http://www.example.org">
...

so if you could supply the raw soap response (so the part from <xml up until <oa:findLibraryResponse ...) you're trying to deserialize, we might figure something out

**Comment by dbclkh** [comment]
Hi Bas,

I got it working with the regular xml deserializer.

The missing link was this in FindLibraryResponse:

      @XmlList(inline=true, entry="pickupAgency")

Thank you very much for your help and time!

Venlig hilsen/Best regards,
Lars Krogsgård Hansen
ProduktUdvikling - Frontend
DBC as

www.dbc.dk<http://www.dbc.dk>
lkh@dbc.dk

Den 29. mar. 2019 kl. 10.22 skrev Lars Krogsgård Hansen <lkh@dbc.dk<mailto:lkh@dbc.dk>>:

Hi Bas,

You’re right - the request is a SOAP but the response isn’t… I am so blind :-(

I’ll give the regular deserializer a go and let you know how it goes.

Venlig hilsen
Lars Krogsgård Hansen
ProduktUdvikling - Frontend
DBC as

www.dbc.dk<http://www.dbc.dk/>
lkh@dbc.dk<mailto:lkh@dbc.dk>

Den 29. mar. 2019 kl. 10.15 skrev wickedOne <notifications@github.com<mailto:notifications@github.com>>:


you're trying to deserialize the "findLibraryResponse", but am quite sure that isn't the raw xml you get from the soap client which should be something like

<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:m="http://www.example.org<http://www.example.org/>">
...

so if you could supply the raw soap response (so the part from <xml up until <oa:findLibraryResponse ...) you're trying to deserialize, we might figure something out

**Comment by proggeler** [comment]
No problem, Lars.
Thx @wickedOne for your time and assistance too.
