### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by victorgp89** [dmt-software/jms-soap-serializer#21]
I think this project is a great idea.

Is it possible to do the same with php 5.6?

Our project uses an old version of jms / serializer therefore we don't have DeserializationVisitorFactory.

In this case is it possible that we can implement our own visitor the same?

**Comment by proggeler** [comment]
@victorgp89 I would advice you to upgrade your server soon. PHP 5.6 is already declared end of live and you does not receive any updates for it not even security updates. So I will not add support for 5.6. But ...

If you can not upgrade at this point you can fork this package and try to change the composer requirements to suit your needs (branch/1.0 might be a nice starting point) and point your composer.json to your new version.

\@see https://stackoverflow.com/a/50317253
